### ISSUE TITLE
question

### ISSUE THREAD

**Issue by chusehwan** [Biswa96/WinLight#1]
hi, when i try to run winlight, i got message like below. can you solve this? (i'm begginer)

UnicodeDecodeError: 'cp949' codec can't decode byte 0xee in position 861: illegal multibyte sequence

**Comment by Biswa96** [comment]
Can you provide the platform and python version you are using? A little search leads me to this utf-8 explanatio https://stackoverflow.com/q/47545946/8928481.

**Comment by Biswa96** [comment]
Can you provide the platform and python version you are using? A little search leads me to this utf-8 explanation https://stackoverflow.com/q/47545946/8928481.

**Comment by Biswa96** [comment]
Fixed by https://github.com/Biswa96/WinLight/pull/2
